# Generated by Django 4.2.1 on 2023-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='word',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
