# Generated by Django 4.2.1 on 2023-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulary', '0002_remove_wordlist_id_alter_wordlist_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='mean',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='word',
            field=models.CharField(max_length=80),
        ),
    ]
